# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: monit ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Git pull
      run: |
          cd /home/simpuskes-monit/htdocs/monit.simpuskes.com
          git pull
    - run: npm install
    - name : change repo
      run : cd /home/simpuskes-monit/htdocs/monit.simpuskes.com/actions-runner/_work/simponi/simponi
    - run : pm2 restart monit.simpuskes.com
    - run : systemctl restart nginx
